### ISSUE TITLE
Load text strips leading zeros from hex

### ISSUE THREAD

**Issue by missinglink** [bdon/s2js-demos#13]
Load text strips leading zeros from hex (making them invalid on subsequent loads):

<img width="279" alt="Screenshot 2024-09-21 at 15 49 04" src="https://github.com/user-attachments/assets/078f3718-d635-44f1-b8ef-9678b9dba9c3">
<img width="279" alt="Screenshot 2024-09-21 at 15 49 16" src="https://github.com/user-attachments/assets/60372afd-7098-469e-af24-d0d875aec426">

example: `055555554`

**Comment by bdon** [comment]
All the internal CellID generation seems to create them without leading zeros, so which should we settle on?

**Comment by missinglink** [comment]
It *should* be generating leading zeros and stripping trailing zeros.

https://github.com/missinglink/s2js/blob/main/s2/cellid_test.ts#L261

**Comment by missinglink** [comment]
https://github.com/missinglink/s2js/blob/590c5899750ad4916658c5071d600788eaf54d1d/s2/cellid.ts#L224

**Comment by missinglink** [comment]
I don't understand where this is happening, is it within the s2js lib?

There doesn't seem to be any place for it to happen within the demo code 🤷‍♂️

https://github.com/bdon/s2js-demos/blob/bdd96bc95aed11b48985b01d8a6ef2948eeeb269/src/App.tsx#L242

**Comment by missinglink** [comment]
The code was old, I must have fixed this bug in https://github.com/missinglink/s2js/releases/tag/v1.43.0, updating the dependency fixed it.
